#!/bin/sh
#
# (c)2009 Christian Kujau <lists@nerdbynature.de>
#
# The therm_adt746x kernel module is not using standard i2c routines
# and we cannot use lm_sensors to request fan or temperature status.
# Instead, when the module is loaded a few /sys objects will be created
# and can be polled as usual.
#
# Examples:
# /sys/devices/temperatures/sensor1_limit:        45
# /sys/devices/temperatures/sensor1_location:     CPU TOPSIDE
# /sys/devices/temperatures/sensor1_temperature:  46
# /sys/devices/temperatures/sensor2_limit:        65
# /sys/devices/temperatures/sensor2_location:     GPU ON DIE
# /sys/devices/temperatures/sensor2_temperature:  61
#
# Plugin wildcard names:
#
#	adt746x_fan	- To monitor fans
#	adt746x_temp	- To monitor temperatures
#
# TODO:
#  - honor munin-node config to adjust warning/critical values
#
if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

# See how we were called (fan/temp)
SENSOR=`basename "$0" | awk -F_ '{print $NF}'`

case $SENSOR in
	fan)
	if [ "$1" = "config" ]; then
		echo 'graph_title Fans'
		echo 'graph_vtitle RPM'
		echo 'graph_args --base 1000 --lower-limit 0'
		echo 'graph_category sensors'
		echo 'graph_info This graph shows the fanspeed'
		echo 'fan1.label Master'
		echo 'fan1.warning 1500:'
		echo 'fan1.critical 1000:'
		exit 0
	fi
	echo "fan1.value `sed 's/.*(//;s/ rpm)$//' < /sys/devices/temperatures/sensor1_fan_speed`"
	;;

	temp)
	if [ "$1" = "config" ]; then
		echo 'graph_title Temperatures'
		echo 'graph_vtitle Celsius'
		echo 'graph_args --base 1000 --lower-limit 0'
		echo 'graph_category sensors'
		echo 'temp1.label CPU TOPSIDE'
		echo 'temp1.warning 48'
		echo 'temp1.critical 50'
		echo 'temp2.label GPU ON DIE'
		echo 'temp2.warning 63'
		echo 'temp2.critical 65'
		exit 0
	fi
	echo "temp1.value `cat /sys/devices/temperatures/sensor1_temperature`"
	echo "temp2.value `cat /sys/devices/temperatures/sensor2_temperature`"
	;;
esac
