#!/bin/sh
#
# (c)2009 Christian Kujau <lists@nerdbynature.de>
# Based on the 'homedirs' plugin, initially written in Perl by Philipp Gruber <pg@flupps.net>
#
# We still need a cronjob to update CACHEFILE once in a while, e.g.:
# 0 * * * * root /usr/bin/du -sk /dir /dir2 dir3/* > /var/run/munin/du_multidirs.cache
#
CACHE=/var/run/munin/du_multidirs.cache

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ ! -f "$CACHE" ]; then
	echo "Cache $CACHE not found!"
	exit 1
fi


if [ "$1" = "config" ]; then
	echo 'graph_title Directory usage (in MB)'
	echo 'graph_args --lower-limit 1 --base 1024'
#	echo 'graph_args --lower-limit 0.01 --logarithmic'
	echo 'graph_vlabel Bytes'
	echo 'graph_category disk'
	echo 'graph_info This graph shows the size of several directories'

	# Munin doesn't like slashes, dots, hyphens and pretty much any symbols in
	# its variables.
	awk -F\	 '!/lost\+found/ {print $2}' $CACHE | sort | while read u; do
		u2=`echo "$u" | sed 's/[[:punct:]]/_/g;s/ /_/g'`
		echo "$u2".label $u
#		echo "$u2".warning 0
#		echo "$u2".critical 0
	done
	exit 0
fi	

awk '!/lost\+found/ {gsub(/\//,"_"); print $2".value "$1 * 1024 }' $CACHE | sort -r -n -k2
# awk -F\	 '!/lost+found/ {print $2".value "$1 * 1024 }' $CACHE | sed 's/[[:punct:]]/_/g' | sort -r -n -k2
