#!/bin/sh
#
# (c)2010 lists@nerdbynature.de
# Get accounting information from a running Tor server.
#
# More info:
# https://gitweb.torproject.org/torspec.git/blob/HEAD:/control-spec.txt
#
[ -z "$conf" ] && conf=/etc/torrc
[ -z "$port" ] && port=9051

if [ "`awk '/^CookieAuthentication/ {print $2}' "$conf"`" = 1 ]; then
	# CookieAuthentication should be set
	COOKIE="`awk '/^CookieAuthFile/ {print $2}' "$conf"`"
#	PASSWORD="`xxd -c 32 -g 0 "$COOKIE" | awk '{print $2}'`"
	PASSWORD="`cat "$COOKIE"`"
else
	# HashedControlPassword should be set
	PASSWORD=$password
fi

if [ "$1" = config ]; then
	echo "graph_title Tor Traffic"
	echo "graph_args --base 1000"
	echo "graph_vlabel bytes in / out"
	echo "graph_category network"
	echo "down.label Download"
        echo "down.type GAUGE"
        echo "up.label Upload"
	echo "up.type GAUGE"
	exit 0
fi

[ -z "$PASSWORD" ] && exit 1
printf "AUTHENTICATE \"${PASSWORD}\"\nGETINFO accounting/bytes\nQUIT" | nc localhost $port | \
	awk -F= '/accounting\/bytes/ {print $2}' | \
	tr -d '\015' | \
	awk '{print "down.value "$1 "\nup.value "$2}'
